server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://192.168.20.63:5432/sentiment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gugr.springboot.entity